### ISSUE TITLE
SSBs estimated by CASAL are consistantly higher than the simulated in IBM

### ISSUE THREAD

**Issue by bianrq** [trophia/sna1#14]
Nokome and Richard will work on it. 

- [ ] plot mean length-at-age, selectivity ogives, catch-at-age etc. 
- [ ] find out what causes the difference in SSBs from the two models

**Comment by bianrq** [comment]
It's hard to compare the two models' selectivity, because IBM's sel is seze-based and CASAL's is age-based. Jeremy will generate a size-based CASAL model.

**Comment by nokome** [comment]
@bianrq and @mckenziej : just to let you know I am looking at this now. Let me know if you have made any further changes that are not yet commited and pushed - just so I don't duplicate your work.

**Comment by bianrq** [comment]
@nokome : nothing new added since about 20 days.
