### ISSUE TITLE
Growth

### ISSUE THREAD

**Issue by nokome** [trophia/sna1#2]
The script https://github.com/trophia/sna1/blob/master/scripts/sna1-growth-indiv-pop.r outlines a way of allowing for individual variation in both the rate of growth and asymptotic length that provides aggregate population level growth that is consistent with von Bert parameters.

Implement this growth model:

- [x] assign individuals a `growth_slope` and `growth_intercept` from a distribution
- [x] growth individuals in each time step according to growth parameters

**Comment by mckenziej** [comment]
Revised the growth model to incorporate lognormal error, this produces log length at-age distributions which is more what you see in the real world. Added a word file to repo that documents the equations and the log-normal growth-path randomisation.

**Comment by nokome** [comment]
Implemented. Note that one of equations in [growth doc](/docs/growth.model.specifications.docx) is wrong (missing negative for slope). I used:

```
        growth_slope = std::exp(-k*time)-1;
        growth_intercept = -growth_slope * linf;
```
