### ISSUE TITLE
Year class strengths currently can only be defined for all regions need to be able to specify different YCS vectors for each model region 

### ISSUE THREAD

**Issue by mckenziej** [trophia/sna1#21]
Year class strengths currently can only be defined for all regions need to be able to specify different YCS vectors for each model region. I.e insert "region" column in fishes_rec_strengths.tsv

**Comment by nokome** [comment]
This is done with f43ab303ba725c3b1c0d2e102a72dda4dead42ae. See https://github.com/trophia/sna1#recruitment-year-class-strengths
