### ISSUE TITLE
Spuriuos starting biomass in EN

### ISSUE THREAD

**Issue by mckenziej** [trophia/sna1#23]
Attached model input files generates a spurious virgin biomass for east northland (EN) 249718 instead of ~200000 (see output file biomass.tsv). The 1901+  EN biomass values are sensible. This may not be a serious bug but code should not do this.

[EN initial biomass error.zip](https://github.com/trophia/sna1/files/1059745/EN.initial.biomass.error.zip)

**Comment by nokome** [comment]
I believe that this is resolved with this five character bug :bug: fix: ad02d4a
