### ISSUE TITLE
Erroneous at-age  CPUE data outputs under individual and mixed growth variation modes 

### ISSUE THREAD

**Issue by mckenziej** [trophia/sna1#24]
The catch at -age and CPUE indices produced by the IBM under individual "i" and mixed "m" growth variation settings appear to be erroneous. One manifestation of the problem is seen in the REC CPUE index which is variable compared to the other method indices. Under temporal growth variation the REC index is smooth. A run where the REC method was given the same selectivity to LL also produced a more variable CPUE trend for REC.

[individual growth variation problem.zip](https://github.com/trophia/sna1/files/1062820/individual.growth.variation.problem.zip)

**Comment by nokome** [comment]
I believe that this is resolved with this five character bug :bug: fix: https://github.com/trophia/sna1/commit/ad02d4aa3b21d0a59b917a635d8c2318339fd717
